projects:
- name: My project
  environments:
  - name: Production
    databases:
    - name: risk2rescue-db
      plan: free
      databaseName: risk2rescue
      user: risk2rescue

    services:
    - type: web
      name: risk2rescue
      runtime: node
      repo: https://github.com/ravadatejeswararao98/risk2rescue
      plan: free
      region: ohio
      buildCommand: npm install
      startCommand: node server.js
      autoDeployTrigger: commit
      envVars:
      - key: DB_HOST
        fromDatabase:
          name: risk2rescue-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: risk2rescue-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: risk2rescue-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: risk2rescue-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: risk2rescue-db
          property: database
      - key: REDIS_URL
        fromService:
          name: risk2rescue-redis
          type: keyvalue
          property: connectionString

    - type: keyvalue
      name: risk2rescue-redis
      plan: free
      maxmemoryPolicy: allkeys-lru
      ipAllowList: []